name: deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be deployed'
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checks out code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          always-auth: true
          registry-url: https://npm.pkg.github.com
      - run: npm i @rbelmega/crypto-trade@${{ github.event.inputs.tag }}
      
      - name: Deploying to S3
        uses: Reggionick/s3-deploy@v3.1.1
        with:
          folder: node_modules/@rbelmega/crypto-trade
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}



       
