name: deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be deployed'
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
#      PATHS: "/*"
#      AWS_REGION: "us-east-1"

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          always-auth: true
          registry-url: https://npm.pkg.github.com
      - run: npm i @rbelmega/crypto-trade@${{ github.event.inputs.tag }}

      - name: Deploying to S3
        uses: Reggionick/s3-deploy@v3.1.1
        with:
          folder: node_modules/@rbelmega/crypto-trade
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.DISTRIBUTION }}
          invalidation: /*
#      - name: Invalidate CloudFront
#        uses: chetan/invalidate-cloudfront-action@v2
#
#
#
#
#
