name: deploy
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be deployed'
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - run: |
          npm i @rbelmega/crypto-trade@${{ github.event.inputs.tag }}
