name: SPA CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - run: yarn run lint
      - run: yarn test

  semantic-release:
      runs-on: ubuntu-latest
      needs: [setup]
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 16
          uses: actions/setup-node@v2
          with:
            node-version: 16
            cache: 'yarn'
        - run: yarn install
        - run: yarn run build
        - run: cp "package.json" "./build/package.json"
        - run: zip -r build.zip build
        - run: yarn semantic-release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - run: cp "./build/package.json" "package.json"
#        - run: |
#            git config user.name "${{ secrets.USERNAME }}"
#            git config user.email "${{ secrets.USEREMAIL }}"
#        - run: |
#            git add package.json
#            git commit -m "chore(release): package.json update [skip ci]"
#            git push origin main
